# keymap/rules.mk
DEFERRED_EXEC_ENABLE = yes
TAP_DANCE_ENABLE = yes
UNICODE_ENABLE = yes
REPEAT_KEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
AUDIO_ENABLE = yes
MIDI_ENABLE = yes
OS_DETECTION_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGBLIGHT_ENABLE = no
CONSOLE_ENABLE = yes
COMBO_ENABLE = yes
